### ISSUE TITLE
Bracket Display for Round Robin and Tournament Gameplay Styles Not Functioning 

### ISSUE THREAD

**Issue by grant19605** [WVU-CS230-2023-01-Group10/GotNext#118]
When the user joins a party that is set up to be a round robin or tournament style game, they should be able to see the bracket representing which teams are in the the tournament as well as the stage the tournament is int. Currently this feature is not functioning as expected as is unviewable by the user and host.

1. Click on 'Join as Player'
2. Enter party code
3. Enter username
4. Select game with round robin or tournament gameplay style
5. Bracket is not viewable

**Comment by grant19605** [comment]
Issue Created By Grant Stumpf

**Comment by nathanmullins11** [comment]
not happening
