### ISSUE TITLE
Check-in button Styling

### ISSUE THREAD

**Issue by jar0095** [WVU-CS230-2023-01-Group10/GotNext#125]
**Describe the bug**
The check-in button needs to be the same style as the other buttons on the page. Right now, it looks different which is causing issues with the styling of the page. Similarly, the button needs to be formatted in reference to the other buttons to give the page a clean and uniform look.

**To Reproduce**
1. Go to queue-page file
2. Click on 'queue-page.component.html
3. Scroll down to line 16 to see the location of the button
4. Head over to queue-page.component.css to style and format the button.

**Expected behavior**
The button should match the style of the other buttons on the page. Also, the buttons should be laid out nicely on the page for a cleaner UI experience for the user. This can be done using bootstrap flex and css styling/formatting.

Name: Joel Robertson

**Comment by ianjackson8** [comment]
Completed by #122
