### ISSUE TITLE
Terminate party button deletes entry 

### ISSUE THREAD

**Issue by ianjackson8** [WVU-CS230-2023-01-Group10/GotNext#38]
**Is your feature request related to a problem? Please describe.**
When the host clicks "Terminate Party" in the Game management page, it deletes the party

**Describe the solution you'd like**
When the host hits the "Terminate Party" a warning pop up should come up confirming if they actually want to terminate the party.
When they confirm, the button triggers an event to delete the associated party from the Firebase backend and routes back to the landing page

**Comment by nathanmullins11** [comment]
@nathanmullins11 finished issue
