### ISSUE TITLE
User input goes to backend following structure

### ISSUE THREAD

**Issue by ianjackson8** [WVU-CS230-2023-01-Group10/GotNext#41]
**Is your feature request related to a problem? Please describe.**
When a user/host inputs their fields, the data is not sent to the backend

**Describe the solution you'd like**
When the user/host inputs data into their fields, send the data into the Firebase database and follow the structure created

**Comment by ianjackson8** [comment]
When a party is created, the post to the Realtime Database follows the approved database model.
Work done by @nathanmullins11, see #59

**Comment by nathanmullins11** [comment]
Done fool
