### ISSUE TITLE
Game name override

### ISSUE THREAD

**Issue by ianjackson8** [WVU-CS230-2023-01-Group10/GotNext#96]
**Describe the bug**
If you create a new game with the same name as an existing game *but different game type*, it over writes the existing game

**To Reproduce**
1. Create a new party
2. Click new game
3. Enter a game name and select a type
4. Create game
5. Create a new game with the same name as the one you created, but with a different play style

**Expected behavior**
A new game with the same name but different type should be added

**Comment by nathanmullins11** [comment]
@nathanmullins11 has completed issue #96 in his branch that needs to be merged with main.
